urls_current = ["https://www.wahlrecht.de/umfragen/allensbach.htm",
              "https://www.wahlrecht.de/umfragen/emnid.htm",
              "https://www.wahlrecht.de/umfragen/forsa.htm",
              "https://www.wahlrecht.de/umfragen/politbarometer.htm",
              "https://www.wahlrecht.de/umfragen/gms.htm",
              "https://www.wahlrecht.de/umfragen/dimap.htm",
              "https://www.wahlrecht.de/umfragen/insa.htm",
                ]



urls_archive= [
       "https://www.wahlrecht.de/umfragen/allensbach/2017.htm",
       "https://www.wahlrecht.de/umfragen/allensbach/2013.htm",
       "https://www.wahlrecht.de/umfragen/allensbach/2009.htm",
       "https://www.wahlrecht.de/umfragen/allensbach/2005.htm",
       "https://www.wahlrecht.de/umfragen/allensbach/2002.htm",
       "https://www.wahlrecht.de/umfragen/emnid/1998.htm",
       "https://www.wahlrecht.de/umfragen/emnid/1999.htm",
       "https://www.wahlrecht.de/umfragen/emnid/2000.htm",
       "https://www.wahlrecht.de/umfragen/emnid/2001.htm",
       "https://www.wahlrecht.de/umfragen/emnid/2002.htm",
       "https://www.wahlrecht.de/umfragen/emnid/2003.htm",
       "https://www.wahlrecht.de/umfragen/emnid/2004.htm",
       "https://www.wahlrecht.de/umfragen/emnid/2005.htm",
       "https://www.wahlrecht.de/umfragen/emnid/2006.htm",
       "https://www.wahlrecht.de/umfragen/emnid/2007.htm",
       "https://www.wahlrecht.de/umfragen/emnid/2008.htm",
       "https://www.wahlrecht.de/umfragen/emnid/2013.htm",
       "https://www.wahlrecht.de/umfragen/forsa/1998.htm",
       "https://www.wahlrecht.de/umfragen/forsa/1999.htm",
       "https://www.wahlrecht.de/umfragen/forsa/2000.htm",
       "https://www.wahlrecht.de/umfragen/forsa/2001.htm",
       "https://www.wahlrecht.de/umfragen/forsa/2002.htm",
       "https://www.wahlrecht.de/umfragen/forsa/2003.htm",
       "https://www.wahlrecht.de/umfragen/forsa/2004.htm",
       "https://www.wahlrecht.de/umfragen/forsa/2005.htm",
       "https://www.wahlrecht.de/umfragen/forsa/2006.htm",
       "https://www.wahlrecht.de/umfragen/forsa/2007.htm",
       "https://www.wahlrecht.de/umfragen/forsa/2008.htm",
       "https://www.wahlrecht.de/umfragen/forsa/2013.htm",
       "https://www.wahlrecht.de/umfragen/politbarometer/politbarometer-1998.htm",
       "https://www.wahlrecht.de/umfragen/politbarometer/politbarometer-2002.htm",
       "https://www.wahlrecht.de/umfragen/politbarometer/politbarometer-2005.htm",
       "https://www.wahlrecht.de/umfragen/politbarometer/politbarometer-2009.htm",
       "https://www.wahlrecht.de/umfragen/politbarometer/politbarometer-2013.htm",
       "https://www.wahlrecht.de/umfragen/politbarometer/politbarometer-2017.htm",
       "https://www.wahlrecht.de/umfragen/gms/projektion-2005.htm",
       "https://www.wahlrecht.de/umfragen/gms/projektion-2009.htm",
       "https://www.wahlrecht.de/umfragen/gms/projektion-2013.htm",
       "https://www.wahlrecht.de/umfragen/gms/projektion-2017.htm",
       "https://www.wahlrecht.de/umfragen/dimap/1998.htm",
       "https://www.wahlrecht.de/umfragen/dimap/1999.htm",
       "https://www.wahlrecht.de/umfragen/dimap/2000.htm",
       "https://www.wahlrecht.de/umfragen/dimap/2001.htm",
       "https://www.wahlrecht.de/umfragen/dimap/2002.htm",
       "https://www.wahlrecht.de/umfragen/dimap/2003.htm",
       "https://www.wahlrecht.de/umfragen/dimap/2004.htm",
       "https://www.wahlrecht.de/umfragen/dimap/2005.htm",
       "https://www.wahlrecht.de/umfragen/dimap/2006.htm",
       "https://www.wahlrecht.de/umfragen/dimap/2007.htm",
       "https://www.wahlrecht.de/umfragen/dimap/2008.htm",
       "https://www.wahlrecht.de/umfragen/dimap/2013.htm",
       "https://www.wahlrecht.de/umfragen/insa/2013.htm",
       "https://www.wahlrecht.de/umfragen/insa/2017.htm",
       "https://www.wahlrecht.de/umfragen/insa/2021.htm"
       ]

urls = urls_current + urls_archive